// Generated by CoffeeScript 1.7.1
'use strict';
module.exports.filter = function(data) {
  var datas;
  datas = [];
  data.ispc = true;
  datas.push({
    filename: "demo5_pc",
    data: data
  });
  data = JSON.parse(JSON.stringify(data));
  data.ispc = false;
  datas.push({
    filename: "demo5_mobile",
    data: data
  });
  return datas;
};
